spring:
  application:
    name: robot-monitoring-backend

server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: health,info

influxdb:
  url: ${INFLUXDB_URL}
  token: ${INFLUXDB_TOKEN}
  org: ${INFLUXDB_ORG}
  bucket: ${INFLUXDB_BUCKET}